port: 8080
resourseTimeout: 30
analyticsTimeout: 30

DBSettings:
  DBUser: "postgres"
  DBPassword: "postgres"
  DBHost: "host.docker.internal"
  DBPort: "5432"
  DBName: "testdb"

ProgramSettings:
  JiraURL: "https://jfrog.atlassian.net"
  ThreadCount: 10
  IssueInOneRequest: 100
  MaxTimeSleep: 2000
  MinTimeSleep: 500
