FROM golang:latest

WORKDIR /golang-coursework

RUN mkdir backend
RUN mkdir backend/gateway 

COPY go.mod go.sum ./
RUN go mod download

COPY backend/gateway ./backend/gateway

RUN go build -o backend/gateway/run ./backend/gateway/cmd/app/main.go

ENV LOG_DIR=/backend/gateway/logs

RUN mkdir -p $LOG_DIR

CMD ["./backend/gateway/run"]