version: '3.8'
services:
  db:
    image: postgres:13.8
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - ./volumes/initdb:/docker-entrypoint-initdb.d
      - ./configs/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 4G

  pgadmin:
    image: dpage/pgadmin4:5.7
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pguser@mail.ru
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'